// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlizqpgbbmlorgkgnilf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsaXpxcGdiYm1sb3Jna2duaWxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyODA2NzEsImV4cCI6MjA2MDg1NjY3MX0.ks6LzMpPiTZDR4ejeBOaD0qn4wawF8MRm2ypIfzdBGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);